name: InvStorage
version: '${project.version}'
main: org.reriva.invstorage.InvStorage
api-version: 1.13

commands:
  invsee:
  invstoragereload:
  endersee:
  invshare:
  endershare:
  invset:
  enderset:
